/* Fachbegriffe in einfacher Sprache (Nutzerwunsch 08.10.2026: „für jedes Kind verständlich“; Ansprache „Sie“ seit 09.10.2026).
   Nur Begriffserklärungen, keine Rechts- oder Steuerberatung. Zahlen nur, wenn sie geprüft auf der Seite stehen.
   w: Wörter, nach denen in Feldbeschriftungen gesucht wird (das erste passende gewinnt; Reihenfolge zählt).
   nurAnfang: nur wenn die Beschriftung mit dem Wort beginnt (z. B. nicht bei „Fixkosten (ohne Kredit)“).
   kurz: Halbsatz in Alltagssprache, steht sichtbar unter der Beschriftung (Welle 1, 09.10.2026).
   e: die lange Erklärung hinter dem (?).
   app.js hängt an passende Beschriftungen ein (?) an und setzt den Halbsatz darunter. */
window.DATEN = window.DATEN || {};
/* Begriffe für „Grundriss und Einrichtung“ (08.10.2026) stehen am Ende der Liste. Die Felder im
   Auswahlkasten des Grundrisses entstehen erst beim Anklicken und bekommen darum kein (?);
   ihre Erklärung steht direkt darunter. */
window.DATEN.begriffe = [
  { w: ['Kaufpreis'], nurAnfang: true, t: 'Kaufpreis', kurz: 'Das zahlen Sie dem Verkäufer, ohne Nebenkosten.', e: 'Der Preis aus dem Exposé. Die Kaufnebenkosten (Grunderwerbsteuer, Notar, Grundbuch, Makler) kommen noch dazu und werden hier dazugerechnet.' },
  { w: ['Grunderwerbsteuer'], t: 'Grunderwerbsteuer', kurz: 'Eine Steuer, die Sie beim Kauf einmal zahlen.', e: 'Eine Steuer, die Sie beim Kauf einmal an das Bundesland zahlen. Wie hoch sie ist, hängt vom Bundesland ab; der Satz steht in der Auswahl „Bundesland“.' },
  { w: ['Notar und Grundbuch'], t: 'Notar und Grundbuch', kurz: 'Gebühren für Vertrag und Eintrag als Eigentümer.', e: 'Der Notar beurkundet den Kaufvertrag. Das Grundbuchamt trägt Sie danach als neuen Eigentümer ein. Beides kostet Gebühren, die zum Kaufpreis dazukommen.' },
  { w: ['Makler', 'Maklerprovision'], t: 'Makler', kurz: 'Die Vermittlungsgebühr, falls ein Makler beteiligt ist.', e: 'Wenn ein Makler das Haus vermittelt, bekommt er eine Provision. Wie hoch sie ist, steht im Angebot (Exposé).' },
  { w: ['Eigenes Geld', 'Eigenkapital'], t: 'Eigenes Geld (Eigenkapital)', kurz: 'Geld, das Sie selbst einsetzen. Den Rest leiht die Bank.', e: 'Das Geld, das Sie selbst mitbringen. Alles andere leihen Sie sich bei der Bank. Je mehr eigenes Geld, desto kleiner sind Kredit und Rate.' },
  { w: ['Kaufnebenkosten'], t: 'Kaufnebenkosten', kurz: 'Alles, was zum Kaufpreis noch dazukommt.', e: 'Alles, was zum Kaufpreis dazukommt: Grunderwerbsteuer, Notar, Grundbuch und, falls es einen gibt, der Makler.' },
  { w: ['Gesamtkosten'], t: 'Gesamtkosten', kurz: 'So viel Geld brauchen Sie insgesamt.', e: 'Kaufpreis plus Nebenkosten plus Renovierung. So viel Geld brauchen Sie insgesamt.' },
  { w: ['Finanzierungsquote'], t: 'Finanzierungsquote', kurz: 'Wie viel vom Kaufpreis die Bank bezahlt.', e: 'Kredit geteilt durch Kaufpreis. Über 100 % heißt: Die Bank soll auch die Nebenkosten mitbezahlen. Das machen nicht alle Banken.' },
  { w: ['Kredit', 'Darlehen'], nurAnfang: true, t: 'Kredit (Darlehen)', kurz: 'Das Geld, das Ihnen die Bank leiht.', e: 'Das Geld, das Ihnen die Bank leiht: Gesamtkosten minus Ihr eigenes Geld.' },
  { w: ['Sollzins'], t: 'Sollzins', kurz: 'Der Preis fürs geliehene Geld pro Jahr.', e: 'Der Preis für das geliehene Geld, in Prozent pro Jahr.' },
  { w: ['Tilgung'], t: 'Tilgung', kurz: 'Der Teil der Rate, der die Schuld wirklich senkt.', e: 'Der Teil der Rate, mit dem Sie die Schuld wirklich abbezahlen. Die anfängliche Tilgung in Prozent sagt, wie schnell es am Anfang geht.' },
  { w: ['Restschuld'], t: 'Restschuld', kurz: 'Was Sie der Bank nach der Festzeit noch schulden.', e: 'Was Sie der Bank am Ende der Zinsbindung noch schulden. Dafür brauchen Sie dann einen neuen Kredit oder eine Anschlussfinanzierung.' },
  { w: ['Zins nach der Zinsbindung', 'Anschlusszins'], t: 'Zins nach der Zinsbindung', kurz: 'Der neue Zins, wenn die Festzeit endet.', e: 'Der Zins, den die Bank verlangt, wenn die Zinsbindung vorbei ist. Heute weiß niemand, wie hoch er dann sein wird. Darum spielt Schritt 4 einen höheren Zins durch.' },
  { w: ['Zinsbindung'], t: 'Zinsbindung', kurz: 'So lange bleibt der Zins fest.', e: 'So viele Jahre bleibt der Zins fest. Danach gilt ein neuer Zins, der höher oder niedriger sein kann.' },
  { w: ['Rate im Monat', 'Monatsrate'], t: 'Rate im Monat', kurz: 'Was Sie jeden Monat an die Bank zahlen.', e: 'Was Sie jeden Monat an die Bank zahlen: Zinsen plus Tilgung. Bei diesem Kredit (Annuitätendarlehen) bleibt sie gleich hoch; mit der Zeit wird der Zinsanteil kleiner und der Tilgungsanteil größer.' },
  { w: ['Kaltmiete'], t: 'Kaltmiete', kurz: 'Die Miete ohne Heizung und Nebenkosten.', e: 'Die Miete ohne Heizung und ohne Nebenkosten wie Wasser oder Müll.' },
  { w: ['Nicht umlagefähige', 'Nicht umgelegte Betriebskosten'], t: 'Nicht umlagefähige Kosten', kurz: 'Kosten, die Sie als Vermieter selbst tragen.', e: 'Kosten, die Sie als Vermieter selbst tragen und nicht über die Nebenkosten an die Mieter weitergeben dürfen, zum Beispiel Verwaltung oder Kontoführung.' },
  { w: ['Instandhaltungsrücklage'], t: 'Instandhaltungsrücklage', kurz: 'Geld für spätere Reparaturen, jeden Monat zurückgelegt.', e: 'Geld, das Sie jeden Monat für spätere Reparaturen zur Seite legen, zum Beispiel für Dach, Heizung oder Fenster.' },
  { w: ['Mietausfall', 'Mietausfallwagnis'], t: 'Mietausfall und Leerstand', kurz: 'Ein Puffer für leere Monate oder ausbleibende Miete.', e: 'Ein Puffer für Monate, in denen eine Wohnung leer steht oder ein Mieter nicht zahlt.' },
  { w: ['Bruttorendite', 'Bruttomietrendite'], t: 'Bruttorendite', kurz: 'Jahresmiete durch Kaufpreis, ohne Kosten.', e: 'Jahresmiete geteilt durch Kaufpreis. Eine schnelle erste Zahl zum Vergleichen; Kosten sind darin noch nicht abgezogen.' },
  { w: ['Nettorendite', 'Nettomietrendite'], t: 'Nettorendite', kurz: 'Wie Bruttorendite, aber nach den laufenden Kosten.', e: 'Was von der Jahresmiete nach den laufenden Kosten übrig bleibt, geteilt durch die Gesamtkosten. Genauer als die Bruttorendite.' },
  { w: ['Kaufpreisfaktor'], t: 'Kaufpreisfaktor', kurz: 'Wie viele Jahresmieten das Haus kostet.', e: 'Wie viele Jahresmieten das Haus kostet: Kaufpreis geteilt durch Jahreskaltmiete. Ein kleinerer Faktor heißt: günstiger im Verhältnis zur Miete.' },
  { w: ['Reinertrag'], t: 'Reinertrag', kurz: 'Miete nach Abzug der laufenden Kosten.', e: 'Die Miete nach Abzug von Leerstand, nicht umlagefähigen Kosten und Rücklage, aber noch vor der Kreditrate.' },
  { w: ['Bleibt im Monat', 'Cashflow'], t: 'Bleibt im Monat (Cashflow)', kurz: 'Was am Monatsende übrig bleibt oder fehlt.', e: 'Was am Monatsende übrig bleibt oder fehlt: Reinertrag minus Kreditrate, vor Steuern. Ein Minus heißt, Sie legen jeden Monat Geld dazu.' },
  { w: ['Bodenrichtwert'], t: 'Bodenrichtwert', kurz: 'Durchschnittspreis für einen Quadratmeter Bauland.', e: 'Was ein Quadratmeter Bauland in der Gegend im Durchschnitt wert ist. Der Gutachterausschuss ermittelt ihn; Sie können ihn kostenlos im Portal BORIS nachsehen.' },
  { w: ['Ertragswert'], t: 'Ertragswert', kurz: 'Wert, der sich aus den Mieten ergibt.', e: 'Ein Wert, der aus den Mieten berechnet wird, die das Haus bringen kann. So bewertet man üblicherweise Mietshäuser.' },
  { w: ['Sachwert'], t: 'Sachwert', kurz: 'Wert aus Baukosten und Grundstück.', e: 'Ein Wert aus dem, was das Gebäude heute zu bauen kosten würde (abzüglich Alter), plus dem Wert des Grundstücks.' },
  { w: ['Vergleichswert', 'Vergleichspreis'], t: 'Vergleichswert', kurz: 'Wert nach den Preisen ähnlicher Häuser.', e: 'Ein Wert aus den Preisen ähnlicher Häuser in der Gegend.' },
  { w: ['Liegenschaftszins', 'Liegenschaftszinssatz'], t: 'Liegenschaftszins', kurz: 'Zinssatz, mit dem Gutachter Mieten in Wert umrechnen.', e: 'Ein Zinssatz, mit dem Gutachter aus den Mieten einen Wert machen. Je niedriger er ist, desto höher kommt der Wert heraus. Der Gutachterausschuss veröffentlicht ihn für die Region.' },
  { w: ['Gesamtnutzungsdauer'], t: 'Gesamtnutzungsdauer', kurz: 'So viele Jahre hält ein Haus dieser Art insgesamt.', e: 'Wie viele Jahre ein Gebäude dieser Art insgesamt üblicherweise genutzt wird.' },
  { w: ['Restnutzungsdauer'], t: 'Restnutzungsdauer', kurz: 'So viele Jahre kann das Haus noch genutzt werden.', e: 'Wie viele Jahre das Gebäude voraussichtlich noch wirtschaftlich genutzt werden kann. Eine Modernisierung kann sie verlängern.' },
  { w: ['Brutto-Grundfläche'], t: 'Brutto-Grundfläche', kurz: 'Alle Geschosse zusammen, außen gemessen.', e: 'Die Fläche aller Geschosse, außen gemessen. Sie steht in den Bauunterlagen.' },
  { w: ['Modernisierung'], t: 'Modernisierung', kurz: 'Ein Umbau, der das Haus verbessert.', e: 'Ein Umbau, der das Haus verbessert, zum Beispiel Dämmung oder ein neues Bad. Danach darf die Miete bei bestehenden Verträgen in Grenzen steigen; reine Reparaturen zählen nicht dazu.' },
  { w: ['Belegung'], t: 'Belegung', kurz: 'Wie viele Betten im Schnitt bezahlt belegt sind.', e: 'Wie viel Prozent der Betten im Durchschnitt pro Nacht bezahlt belegt sind.' },
  { w: ['Wohnfläche'], nurAnfang: true, t: 'Wohnfläche', kurz: 'Die Fläche, die als Wohnraum zählt.', e: 'Die Fläche, die als Wohnraum zählt. Stellen unter einer Dachschräge, die niedriger als 2 m sind, zählen nur halb, unter 1 m gar nicht. Balkone zählen meist zu einem Viertel. Keller und Garage zählen nicht. So steht es in der Wohnflächenverordnung.' },
  { w: ['Nutzfläche'], nurAnfang: true, t: 'Nutzfläche', kurz: 'Keller, Garage und Co., keine Wohnfläche.', e: 'Flächen, die keine Wohnfläche sind, aber genutzt werden können: Keller, Garage, Heizraum, Abstellraum. Manche davon kann man extra vermieten.' },
  { w: ['Echte Länge'], t: 'Maßstab', kurz: 'Eine bekannte Strecke macht das Bild maßstabsgetreu.', e: 'Ein Bild weiß nicht, wie groß das Haus wirklich ist. Sie zeigen der Seite eine Strecke, deren Länge Sie kennen, und sagen, wie lang sie in echt ist. Danach stimmen alle Flächen.' },
  { w: ['Gebäudeanteil'], t: 'Gebäudeanteil', kurz: 'Wie viel vom Preis auf das Haus fällt, nicht auf den Boden.', e: 'Beim Kauf bezahlen Sie Haus und Boden zusammen. Abschreiben dürfen Sie nur das Haus, denn der Boden nutzt sich nicht ab. Der Gebäudeanteil sagt, wie viel vom Preis auf das Haus fällt. Das Finanzamt rechnet ihn mit einer eigenen Hilfe aus.' },
  { w: ['persönlicher Steuersatz'], t: 'Persönlicher Steuersatz', kurz: 'Steuer auf jeden zusätzlich verdienten Euro.', e: 'Wie viel Prozent Steuer Sie auf einen zusätzlich verdienten Euro zahlen. Er hängt von Ihrem ganzen Einkommen ab. Wenn Sie ihn nicht kennen: Steuerberater fragen oder einen amtlichen Steuerrechner nutzen.' },
  { w: ['Wertsteigerung des Hauses'], t: 'Wertsteigerung', kurz: 'Um wie viel Prozent das Haus pro Jahr mehr wert wird.', e: 'Um wie viel Prozent das Haus jedes Jahr mehr wert wird. Das weiß niemand vorher. Probieren Sie auch 0 % oder einen Minuswert aus, um zu sehen, was dann passiert.' },
  { w: ['Mietsteigerung'], t: 'Mietsteigerung', kurz: 'Um wie viel Prozent die Miete pro Jahr steigt.', e: 'Um wie viel Prozent die Miete im Schnitt jedes Jahr steigt. Wie stark Sie die Miete erhöhen dürfen, regelt das Mietrecht (zum Beispiel Mietspiegel und Kappungsgrenze).' }
];
