/* Umbau und Sanierung: Kostenspannen, Förderprogramme, Bauablauf.
   Quelle der Kosten: Recherche 07 (werkzeuge/recherche/07_sanierung_foerderung.md), Abruf 07.10.2026.
   Quelle der Förderprogramme KfW 261, BEG Einzelmaßnahmen und Bremen: Recherche 03b (werkzeuge/recherche/03b_rechtsform_foerderung_nacharbeit.md, Abschnitt 3), Abruf 09.10.2026.
   haupt: true = Bauteil steht auf dem ersten Bildschirm, die übrigen unter „Mehr Einstellungen“.
   kurz: Halbsatz in Alltagssprache unter dem Namen (Abkürzungen).
   Kosten nur aus Ratgeber- und Anbieterseiten: Größenordnung, durch echte Angebote ersetzen.
   Startpreis je Zeile = Mitte der kleinsten genannten Spanne (eigene Wahl, im Rechner änderbar). */
window.DATEN = window.DATEN || {};
window.DATEN.sanierung = {
  abruf: '2026-10-07',
  bauteile: [
    { id: 'dach', haupt: true, name: 'Dach neu eindecken inkl. Dämmung', einheit: 'm² Dachfläche', von: 95, bis: 250, start: 160, quelle: 'clean-invoice.com (2026); whk-controlling.de (13.04.2026, netto)' },
    { id: 'fassade', haupt: true, name: 'Fassadendämmung WDVS', kurz: 'WDVS heißt Wärmedämm-Verbundsystem: Dämmplatten außen an der Wand, darüber Putz.', einheit: 'm² Wandfläche', von: 130, bis: 250, start: 165, quelle: 'Commerzbank-Ratgeber (06.01.2025); reduco.ai, clean-invoice.com, whk-controlling.de (2026)' },
    { id: 'fenster', haupt: true, name: 'Fenster tauschen (3-fach, inkl. Einbau)', einheit: 'Stück', von: 500, bis: 900, start: 700, quelle: 'reduco.ai (2026); whk-controlling.de (13.04.2026, netto)' },
    { id: 'gas', name: 'Heizung Gas-Brennwert (Anlage)', einheit: 'Anlage', von: 9000, bis: 17000, start: 13000, quelle: 'Suchtreffer-Auszüge 2026, Original nicht geprüft (unsicher)' },
    { id: 'wp', name: 'Wärmepumpe Luft/Wasser (Anlage, Einfamilienhaus-Größe)', einheit: 'Anlage', von: 14000, bis: 47000, start: 30000, quelle: 'reduco.ai; whk-controlling.de; clean-invoice.com (2026), sehr breite Streuung' },
    { id: 'elektrik', name: 'Elektrik erneuern (Standard)', einheit: 'm² Wohnfläche', von: 80, bis: 150, start: 110, quelle: 'clean-invoice.com, my-hammer.de (2026); whk-controlling.de (netto)' },
    { id: 'bad', haupt: true, name: 'Bad komplett (Standard)', einheit: 'Bad', von: 16000, bis: 28000, start: 20000, quelle: 'clean-invoice.com (2026); Suchtreffer-Auszüge 2026' },
    { id: 'leitungen', name: 'Wasser- und Abwasserleitungen', einheit: 'm² Wohnfläche', von: 60, bis: 100, start: 80, quelle: 'whk-controlling.de (13.04.2026, netto)' },
    { id: 'boden', name: 'Böden', einheit: 'm²', von: 45, bis: 140, start: 80, quelle: 'clean-invoice.com (2026)' },
    { id: 'putz', name: 'Innenputz, Trockenbau', einheit: 'm²', von: 40, bis: 80, start: 60, quelle: 'whk-controlling.de (13.04.2026, netto)' },
    { id: 'keller', name: 'Kellerabdichtung (Horizontalsperre)', einheit: 'lfd. m', von: 120, bis: 250, start: 180, quelle: 'clean-invoice.com, bau.de (2026, Suchtreffer)' },
    { id: 'tueren', name: 'Innentüren mit Zarge und Einbau', einheit: 'Stück', von: 250, bis: 500, start: 350, quelle: 'clean-invoice.com, kuechenfibel.de (2026); whk-controlling.de' },
    { id: 'kern', name: 'Kernsanierung gesamt (statt Einzelpositionen)', einheit: 'm² Wohnfläche', von: 700, bis: 2500, start: 1200, quelle: 'reduco.ai (24.08.2026); clean-invoice.com; whk-controlling.de' }
  ],
  zuschlaege: {
    planung: { start: 13, text: 'Planung 12 bis 15 % der Baukosten (whk-controlling.de, 13.04.2026)' },
    baustelle: { start: 7, text: 'Baustelleneinrichtung und Entsorgung 5 bis 10 % (whk-controlling.de, 13.04.2026)' },
    puffer: { start: 15, text: 'Puffer für Unvorhergesehenes im Altbau 15 bis 20 % (whk-controlling.de; clean-invoice.com, 2026)' }
  },
  foerderung: [
    { name: 'BAFA/KfW Einzelmaßnahmen (BEG EM: Dach, Fassade, Fenster, Heizung)', kurz: 'BEG heißt Bundesförderung für effiziente Gebäude, das Förderprogramm des Bundes. iSFP heißt individueller Sanierungsfahrplan: ein Plan des Energieberaters, was in welcher Reihenfolge saniert wird.', hoehe: 'Vor Nutzung prüfen (laut Recherchebericht, nicht am Original bestätigt): Gebäudehülle und Anlagentechnik außer Heizung 15 %; iSFP-Bonus +5 Prozentpunkte nur auf den Teil der Ausgaben über 30.000 € (erste Wohneinheit). Höchstgrenze 30.000 € erste Wohneinheit, 60.000 € mit iSFP (je 15.000 € bzw. 30.000 € für Wohneinheit 2 bis 6, je 8.000 € bzw. 15.000 € ab Wohneinheit 7). Wärmepumpen-Grundförderung ab 2027 niedriger (vor Nutzung prüfen). Den Klimageschwindigkeits-Bonus und den Einkommens-Bonus erhalten nur selbstnutzende Eigentümer für die selbst genutzte Wohneinheit, Vermieter nicht (Nr. 8.4.4 und 8.4.5).', vermieter: 'ja, antragsberechtigt (Nr. 6.1: alle Investoren, auch private Hauseigentümer und Unternehmen), aber ohne die Boni für Selbstnutzer', vorher: 'Antrag vor Vorhabenbeginn; bei Antrag muss ein Liefer-/Leistungsvertrag mit Bedingung der Förderzusage vorliegen; Beginn vor Zusage nur auf eigenes Risiko', status: 'Antragsberechtigung belegt (Förderrichtlinie BEG EM vom 17.08.2026, Bundesanzeiger 27.08.2026, Nr. 6.1, 8.3.1, 8.4.1, 9.2.1, Abruf 09.10.2026); Fördersätze und iSFP-Bonus aus Recherchebericht 16, vor Nutzung auf bafa.de prüfen', url: 'https://www.bafa.de/DE/Energie/Effiziente_Gebaeude/Sanierung_Wohngebaeude/sanierung_wohngebaeude_node.html' },
    { name: 'KfW 261 Wohngebäude Kredit (Sanierung zum Effizienzhaus)', kurz: 'EH heißt Effizienzhaus (je kleiner die Zahl, desto weniger Energie braucht das Haus). EE heißt: mit Erneuerbare-Energien-Klasse.', hoehe: 'Kredit bis 150.000 € je Wohneinheit. Tilgungszuschuss (der Teil des Kredits, den Sie nicht zurückzahlen): EH 40 EE 10 %, EH 55 EE 5 %, Effizienzhaus Denkmal EE 5 %, EH 70 EE und EH 85 EE 0 %. Zuschläge sind möglich, zum Beispiel 5 Prozentpunkte für die Nachhaltigkeitsklasse (KfW-Merkblatt 261, Stand 09/2026, Abruf 09.10.2026).', vermieter: 'ja: antragsberechtigt sind Privatpersonen und Unternehmen, auch Einzelunternehmer; Vermietung wird nicht ausgeschlossen. Gefördert wird nur die Sanierung zum Effizienzhaus oder der Ersterwerb eines frisch sanierten Gebäudes, nicht der Kauf eines unsanierten Hauses.', vorher: 'Antrag über die Hausbank vor Vorhabenbeginn, Energieeffizienz-Experte Pflicht; der Bauantrag des Hauses muss mindestens 5 Jahre zurückliegen; 10 Jahre Wohnnutzung nach Fertigstellung', status: 'belegt (KfW-Merkblatt Kredit 261, Stand 09/2026, gültig ab 24.09.2026, Abruf 09.10.2026); Zinssätze nicht abgerufen', url: 'https://www.kfw.de/PDF/Download-Center/F%C3%B6rderprogramme-(Inlandsf%C3%B6rderung)/PDF-Dokumente/6000004854_M_261.pdf' },
    { name: 'KfW 458 Heizungsförderung', kurz: 'zvE heißt zu versteuerndes Einkommen.', hoehe: 'Grundförderung 30 %. Förderfähige Kosten höchstens 28.000 € für die erste Wohneinheit, je 15.000 € für Wohneinheit 2 bis 6, je 8.000 € ab Wohneinheit 7. Mindestinvestition 300 € brutto. Boni gibt es nur noch als Klimageschwindigkeitsbonus und Einkommensbonus (40/30/10 % bis 30.000/40.000/50.000 € zvE), beide nur für Selbstnutzer; einen Effizienzbonus gibt es nicht mehr (KfW-Merkblatt 458, Stand 09/2026, Grundlage BEG EM vom 17.08.2026, Abruf 09.10.2026).', vermieter: 'eingeschränkt: Vermieter erhalten nur die Grundförderung (vor Nutzung prüfen: Folgerung aus den Bonus-Texten). Antragsberechtigt als natürliche Person; ob eine GmbH förderfähig ist, ist offen (vor Nutzung prüfen).', vorher: 'Liefer-/Leistungsvertrag mit aufschiebender oder auflösender Bedingung der KfW-Zusage vor Antragstellung; Antrag vor Vorhabenbeginn', status: 'Beträge belegt (KfW-Merkblatt 458, Stand 09/2026, Abruf 09.10.2026); Aussage zu Vermietern und GmbH vor Nutzung prüfen', url: 'https://www.kfw.de/PDF/Download-Center/F%C3%B6rderprogramme-(Inlandsf%C3%B6rderung)/PDF-Dokumente/6000005131_M_458.pdf' },
    { name: 'BAFA Energieberatung für Wohngebäude (EBW, iSFP)', kurz: 'iSFP heißt individueller Sanierungsfahrplan: ein Plan des Energieberaters, was in welcher Reihenfolge saniert wird.', hoehe: '50 % des Beratungshonorars, höchstens 650 € (Ein- und Zweifamilienhaus) bzw. 850 € (ab drei Wohneinheiten). Laut Recherchebericht endet die Richtlinie am 31.12.2026 (auf der BAFA-Seite nicht gefunden, vor Nutzung prüfen).', vermieter: 'ja', vorher: 'Antrag vor Vorhabenbeginn (Vertragsschluss), nur über das BAFA-Portal', status: 'Beträge belegt (BAFA-Seite Energieberatung für Wohngebäude, Abruf 09.10.2026); Befristung bis 31.12.2026 vor Nutzung prüfen', url: 'https://www.bafa.de/DE/Energie/Energieberatung/Energieberatung_Wohngebaeude/energieberatung_wohngebaeude_node.html' },
    { name: 'Bremen: Modernisierung von Mietwohnraum (Bremer Aufbau-Bank)', kurz: 'WBS heißt Wohnberechtigungsschein: Nur Mieter mit diesem Schein dürfen einziehen.', hoehe: 'Zinsloses Darlehen bis 80 % der Kosten, höchstens 150.000 € je Wohneinheit, dazu ein Zuschuss je Wohneinheit nach Energiestandard: EH 85 25.000 €, EH 70 27.500 €, EH 55 32.500 €, EH 40 35.000 € (mit EE-Klasse 30.000 bis 40.000 €). Darlehen und Zuschuss zusammen höchstens 90 % der Gesamtkosten; Eigenleistung mindestens 15 %, davon mindestens 10 % echtes Eigenkapital (Richtlinie vom 27.08.2026, Nr. 4.1, 5.1 und 5.2, Abruf 09.10.2026).', vermieter: 'ja, ausdrücklich, ohne Einschränkung der Rechtsform. Bedingungen: nur Gebäude mit mehr als zwei geförderten Mietwohnungen, mindestens Effizienzhaus 85, Wohnraum mindestens 25 Jahre bezugsfertig (Nr. 1.1, 7.1, 7.2)', vorher: 'Anmeldung vor Baubeginn', bindung: 'Mietobergrenze: Nettokaltmiete höchstens 6,80 € je m² Wohnfläche (Ein-Zimmer-Apartments 7,50 €), 20 Jahre lang. Nur an Mieter mit Wohnberechtigungsschein (WBS), deren Einkommen höchstens 70 % über der Grenze des § 9 Abs. 2 WoFG liegt. Eigenbedarf und Umwandlung in Eigentumswohnungen sind in der Regel ausgeschlossen. Eine Nutzung als Monteurzimmer ist damit nicht vereinbar (Nr. 6.1, 6.3, 8.1, 8.2, 8.4).', status: 'belegt (Richtlinie Mietwohnraumförderung Modernisierung ab 2026, Senatorin für Bau, Mobilität und Stadtentwicklung, vom 27.08.2026, Abruf 09.10.2026). Die früheren Werte 55.000 € Darlehen und 15.000 € Zuschuss gelten nicht mehr.', url: 'https://bau.bremen.de/sixcms/media.php/13/01b_Richtlinie%2BModernisierung%2Bab%2BWRP%2B2026.pdf' },
    { name: 'Steuerermäßigung § 35c EStG', hoehe: '20 % der Kosten über 3 Jahre, höchstens 40.000 €', vermieter: 'nein, nur Selbstnutzer; bei Vermietung Werbungskosten oder Abschreibung (Steuerberater)', vorher: 'nein', status: 'aktiv (Stand 07.10.2026)', url: 'https://www.gesetze-im-internet.de/estg/__35c.html' },
    { name: 'KfW 124 und 308 (Wohneigentum)', hoehe: 'nur für selbst genutztes Wohneigentum', vermieter: 'nein', vorher: '-', status: 'für Vermieter nicht nutzbar', url: 'https://www.kfw.de' }
  ],
  ablauf: [
    { schritt: 'Planung', inhalt: 'Ziel, Budget, Zeitplan; Mieter früh informieren.', wer: 'Eigentümer' },
    { schritt: 'Bestandsaufnahme', inhalt: 'Zustand, Schadstoffe, tragende Teile.', wer: 'Sachverständiger, bei Bedarf Statiker' },
    { schritt: 'Energieberatung', inhalt: 'Sanierungsfahrplan bzw. Bestätigung für BEG-Förderung; Förderantrag vor jeder Beauftragung.', wer: 'Energieeffizienz-Experte' },
    { schritt: 'Entwurf und Leistungsverzeichnis', inhalt: 'Grundrisse, Maßnahmen, Mengen für Angebote.', wer: 'Architekt oder Planer' },
    { schritt: 'Genehmigung klären', inhalt: 'Bremen: vereinfachtes Verfahren (Entscheidung binnen 12 Wochen nach Vollständigkeit, Antrag digital) oder Genehmigungsfreistellung nach § 62 BremLBO im Bebauungsplangebiet (Gemeinde kann binnen eines Monats widersprechen). Ob eine Maßnahme verfahrensfrei ist (§ 61 BremLBO), bei der Bauaufsicht fragen.', wer: 'Entwurfsverfasser', quelle: 'service.bremen.de, Abruf 07.10.2026' },
    { schritt: 'Statik', inhalt: 'Bei Eingriffen in tragende Teile; Standsicherheitsnachweis gehört zu den Bauvorlagen.', wer: 'Statiker' },
    { schritt: 'Angebote und Vergabe', inhalt: 'Mehrere Angebote je Gewerk; bei Förderung Förderklausel in den Vertrag.', wer: 'Planer, Bauleiter' },
    { schritt: 'Modernisierung ankündigen', inhalt: 'Bei vermieteten Wohnungen spätestens drei Monate vor Beginn in Textform ankündigen (§ 555c BGB); Mieter muss dulden, außer bei Härte (§ 555d BGB).', wer: 'Eigentümer, bei Fragen Rechtsanwalt', quelle: 'gesetze-im-internet.de, Abruf 07.10.2026' },
    { schritt: 'Bauausführung', inhalt: 'Bauleitung, Fotos und Protokolle, Abschlagsrechnungen prüfen.', wer: 'Bauleiter' },
    { schritt: 'Abnahme', inhalt: 'Werk abnehmen; wegen unwesentlicher Mängel darf die Abnahme nicht verweigert werden (§ 640 BGB). Mängel ins Protokoll.', wer: 'Eigentümer, Sachverständiger', quelle: 'gesetze-im-internet.de, Abruf 07.10.2026' },
    { schritt: 'Gewährleistung', inhalt: 'Mängelansprüche verjähren bei Bauwerken nach 5 Jahren ab Abnahme (§ 634a BGB); Fristen notieren.', wer: 'Eigentümer', quelle: 'gesetze-im-internet.de, Abruf 07.10.2026' }
  ]
};
