/* Tipps und Fallen beim Steuern sparen (Block 4, 09.10.2026).
   Inhalt: recherche/14_steuern_sparen.md (Abruf aller Quellen 09.10.2026). Keine Steuerberatung, keine Empfehlung (R078):
   Formulierung „Das Gesetz erlaubt …, mit Steuerberater prüfen“. Paragraphen stammen aus den Gesetzestexten auf gesetze-im-internet.de
   (Überschriften im Bericht geprüft, R007). Was der Bericht „unsicher“ nennt, steht im Feld pruefen und wird als „Vor Nutzung prüfen“ gezeigt (R074).
   Felder je Karte:
     titel, satz (ein Satz in einfacher Sprache), bed (Bedingung), verm ('ja' | 'nein' | Text mit Einschränkung), selbstnutzer (true = nur Selbstnutzer),
     para ([{ t: Text, u: Adresse }]), pruefen (Text oder ''), quelle (Text mit Stand), rechner (Id eines Rechners auf der Seite, optional). */
window.DATEN = window.DATEN || {};
(function () {
  var ABRUF = '09.10.2026';
  function g(gesetz, nr) { return 'https://www.gesetze-im-internet.de/' + gesetz + '/__' + nr + '.html'; }
  function es(nr, name) { return { t: '§ ' + nr + ' EStG' + (name ? ' (' + name + ')' : ''), u: g('estg', nr) }; }
  var BMF_SANIERUNG = { t: 'BMF-Schreiben vom 26.01.2026 (Instandsetzung und Modernisierung von Gebäuden)', u: 'https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Einkommensteuer/2026-01-26-instandsetzung-modernisierung-gebaeude.pdf?__blob=publicationFile' };
  var ESTH_21 = 'https://esth.bundesfinanzministerium.de/esth/2025/A-Einkommensteuergesetz/II-Einkommen-2-24b/8-Die-einzelnen-Einkunftsarten-13-24b/f-Vermietung-und-Verpachtung-21/Paragraf-21/inhalt.html';
  var ESTH_23 = 'https://esth.bundesfinanzministerium.de/esth/2025/A-Einkommensteuergesetz/II-Einkommen-2-24b/8-Die-einzelnen-Einkunftsarten-13-24b/g-Sonstige-Einkuenfte-22-23/Paragraf-23/inhalt.html';
  var BMF_23 = { t: 'BMF-Schreiben vom 05.10.2000 zu § 23 EStG (Anhang 26 der Einkommensteuer-Hinweise)', u: 'https://esth.bundesfinanzministerium.de/esth/2024/C-Anhaenge/Anhang-26/anhang-26.html' };
  var ARBEITSHILFE = { t: 'BMF-Arbeitshilfe zur Kaufpreisaufteilung (Stand März 2026)', u: 'https://www.bundesfinanzministerium.de/Datenportal/Daten/frei-nutzbare-produkte/Anwendungen/Kaufpreisaufteilung-Grundstuecke/Kaufpreisaufteilung-Grundstuecke.html' };

  var gruppen = [
    { id: 'kauf', titel: 'Beim Kauf', text: 'Was schon beim Kaufvertrag und bei der Abschreibung zählt.' },
    { id: 'umbau', titel: 'Beim Umbau und Sanieren', text: 'Reparaturen, Modernisierung, Sanierungsgebiet und Denkmal.' },
    { id: 'vermietung', titel: 'Während der Vermietung', text: 'Was Sie laufend von den Mieteinnahmen abziehen dürfen.' },
    { id: 'verkauf', titel: 'Beim Verkauf', text: 'Die Zehn-Jahres-Frist und was sie für den Gewinn bedeutet.' },
    { id: 'fallen', titel: 'Fallen', text: 'Hier gehen Vorteile verloren. Jede Falle steht auch bei ihrem Thema oben.' }
  ];

  var karten = [
    /* ---------- Kauf ---------- */
    { gruppe: 'kauf', id: 'k-aufteilung', titel: 'Kaufpreis aufteilen: Boden und Gebäude',
      satz: 'Das Gesetz erlaubt die Abschreibung nur für das Gebäude, nie für den Boden; je größer der Gebäudeanteil am Kaufpreis, desto mehr können Sie jedes Jahr abschreiben.',
      bed: 'Der Gesamtkaufpreis wird nach dem Verhältnis der Verkehrswerte von Boden und Gebäude aufgeteilt (BFH-Urteil vom 10.10.2000, IX R 86/97). Die Finanzverwaltung stellt dafür eine Arbeitshilfe bereit.',
      verm: 'ja', para: [es('7', 'Absetzung für Abnutzung'), ARBEITSHILFE],
      pruefen: 'Ob eine Aufteilung im Kaufvertrag das Finanzamt bindet und wie Gerichte mit der Arbeitshilfe umgehen, ist nur aus Zusammenfassungen von Beratungsfirmen belegt.',
      quelle: 'BMF-Datenportal und gesetze-im-internet.de, Abruf ' + ABRUF, rechner: 'st-c' },
    { gruppe: 'kauf', id: 'k-afa', titel: 'Gebäude abschreiben: 2, 2,5 oder 3 Prozent',
      satz: 'Das Gesetz erlaubt, jedes Jahr einen festen Prozentsatz des Gebäudewerts abzuschreiben, ohne dass Geld abfließt; das mindert die Mieteinkünfte.',
      bed: 'Gebäude im Privatvermögen. Satz nach Fertigstellung: ab 2023 jährlich 3 %, von 1925 bis 2022 jährlich 2 %, vor 1925 jährlich 2,5 % der Anschaffungs- oder Herstellungskosten.',
      verm: 'ja', para: [es('7', 'Absatz 4 Satz 1 Nr. 2')], pruefen: 'Die Sätze stammen aus dem Gesetzestext vom 09.10.2026. Ein Referentenentwurf zum Jahressteuergesetz 2026 (19.05.2026) wurde nicht auf Änderungen untersucht.',
      quelle: 'gesetze-im-internet.de (§ 7 EStG), Abruf ' + ABRUF },
    { gruppe: 'kauf', id: 'k-degressiv', titel: 'Neubau: 5 Prozent fallend',
      satz: 'Das Gesetz erlaubt bei neuen Wohngebäuden statt der gleichbleibenden Abschreibung 5 Prozent vom jeweiligen Restwert, jedes Jahr etwas weniger.',
      bed: 'Nur Wohnzwecke; selbst hergestellt oder bis Ende des Jahres der Fertigstellung gekauft; Baubeginn (Baubeginnsanzeige) oder Kaufvertrag nach dem 30.09.2023 und vor dem 01.10.2029. Der Wechsel zur gleichbleibenden Abschreibung ist erlaubt.',
      verm: 'ja, nur Neubau (nicht beim Kauf eines Bestandshauses)', para: [es('7', 'Absatz 5a')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 7 EStG), Abruf ' + ABRUF },
    { gruppe: 'kauf', id: 'k-7b', titel: 'Neubau: Sonderabschreibung nach § 7b',
      satz: 'Das Gesetz erlaubt bei neuen Mietwohnungen zusätzlich bis zu 5 Prozent im Jahr der Fertigstellung und in den drei Folgejahren.',
      bed: 'Neue, bisher nicht vorhandene Wohnungen; Bauantrag nach dem 31.12.2022 und vor dem 01.10.2029; Effizienzhaus 40 mit Nachhaltigkeitssiegel; Baukosten höchstens 5.200 € je m², Bemessungsgrundlage höchstens 4.000 € je m²; zehn Jahre Vermietung zu Wohnzwecken (Beherbergung zählt nicht).',
      verm: 'ja, nur Neubau', para: [es('7b', 'Sonderabschreibung für Mietwohnungsneubau')],
      pruefen: 'Ob der EU-Beihilfe-Nachweis für reine Vermieter nötig ist, folgt nur aus dem Wortlaut (Absatz 5 Satz 2) und gehört zum Steuerberater. Ein Referentenentwurf zum Jahressteuergesetz 2026 (19.05.2026) wurde nicht auf Änderungen untersucht.',
      quelle: 'gesetze-im-internet.de (§ 7b EStG) und BMF-Anwendungsschreiben vom 21.05.2025, Abruf ' + ABRUF },
    { gruppe: 'kauf', id: 'k-kuerzer', titel: 'Kürzere Nutzungsdauer nachweisen',
      satz: 'Das Gesetz erlaubt eine höhere Abschreibung, wenn das Gebäude nachweislich kürzer genutzt werden kann als 50 Jahre (bei Fertigstellung vor 1925: 40 Jahre, ab 2023: 33 Jahre).',
      bed: 'Die kürzere tatsächliche Nutzungsdauer müssen Sie nachweisen, meist mit einem Gutachten gegen Gebühr.',
      verm: 'ja', para: [es('7', 'Absatz 4 Satz 2')],
      pruefen: 'Dass die Verwaltung ihr Schreiben dazu aufgehoben hat und der BFH den Nachweis mit jeder geeigneten Darstellung zulässt, stammt nur aus Zusammenfassungen (Primärquelle fehlt).',
      quelle: 'gesetze-im-internet.de (§ 7 EStG), Abruf ' + ABRUF },
    { gruppe: 'kauf', id: 'k-nebenkosten', titel: 'Kaufnebenkosten: über die Abschreibung, nicht sofort',
      satz: 'Notar, Grundbuch und Grunderwerbsteuer für den Kauf zählen zu den Anschaffungskosten und wirken nur über die Abschreibung; Kosten für die Grundschuld zählen dagegen sofort als Werbungskosten.',
      bed: 'Die Kosten der Darlehensaufnahme (zum Beispiel Notar für die Grundschuld) gehören zu den Schuldzinsen im weiteren Sinn.',
      verm: 'ja', para: [es('9', 'Werbungskosten'), { t: 'Einkommensteuer-Hinweise 2025, H 21.2', u: ESTH_21 }], pruefen: '',
      quelle: 'gesetze-im-internet.de und Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },

    /* ---------- Umbau ---------- */
    { gruppe: 'umbau', id: 'u-erhaltung', titel: 'Reparaturen sofort absetzen',
      satz: 'Das Gesetz erlaubt, Instandsetzung und Modernisierung in aller Regel sofort als Werbungskosten abzuziehen.',
      bed: 'Keine anschaffungsnahen Herstellungskosten (15-%-Grenze, nächste Karte), keine Erweiterung. Auch Schönheitsreparaturen zählen zur Grenze.',
      verm: 'ja', para: [es('9', 'Werbungskosten'), BMF_SANIERUNG], pruefen: '',
      quelle: 'BMF-Schreiben vom 26.01.2026 (Rn. 1, 55), Abruf ' + ABRUF, rechner: 'st-a' },
    { gruppe: 'umbau', id: 'u-15', titel: 'Die 15-Prozent-Grenze in den ersten drei Jahren',
      satz: 'Übersteigen Instandsetzung und Modernisierung in den ersten drei Jahren nach dem Kauf zusammen 15 Prozent der Anschaffungskosten des Gebäudes (ohne Umsatzsteuer), kann das Gesetz sie nur noch über die Abschreibung zulassen.',
      bed: 'Genau 15 Prozent sind noch unschädlich. Nicht mitgezählt: Erweiterungen und jährlich übliche Erhaltungsarbeiten. Die Frist läuft taggenau ab dem Übergang von Besitz, Nutzen und Lasten. Auch Kosten nach § 7h/§ 7i zählen mit (BMF Rn. 66).',
      verm: 'ja', para: [es('6', 'Bewertung, Absatz 1 Nr. 1a'), BMF_SANIERUNG],
      pruefen: 'Die Faustregel „Standardhebung: mindestens drei von vier Bereichen“ stammt nur aus einem Newsletter, nicht aus dem BMF-Schreiben selbst.',
      quelle: 'gesetze-im-internet.de (§ 6 EStG), BMF-Schreiben vom 26.01.2026 (Rn. 62, 63, 66), Abruf ' + ABRUF, rechner: 'st-a' },
    { gruppe: 'umbau', id: 'u-82b', titel: 'Große Reparaturen auf 2 bis 5 Jahre verteilen',
      satz: 'Das Gesetz erlaubt, größeren Erhaltungsaufwand an Wohngebäuden gleichmäßig auf zwei bis fünf Jahre zu verteilen; das glättet Steuerspitzen.',
      bed: 'Gebäude im Privatvermögen, überwiegend zu Wohnzwecken. Wird in dieser Zeit verkauft, geht der Rest im Verkaufsjahr als Werbungskosten ab.',
      verm: 'ja', para: [{ t: '§ 82b EStDV (Behandlung größeren Erhaltungsaufwands bei Wohngebäuden)', u: g('estdv_1955', '82b') }], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 82b EStDV), Abruf ' + ABRUF },
    { gruppe: 'umbau', id: 'u-7h', titel: 'Sanierungsgebiet: 100 Prozent in 12 Jahren',
      satz: 'Das Gesetz erlaubt in einem förmlich festgelegten Sanierungsgebiet, Modernisierungskosten im Jahr der Herstellung und in sieben Folgejahren mit bis zu 9 Prozent, danach vier Jahre mit bis zu 7 Prozent abzusetzen.',
      bed: 'Förmliches Sanierungsgebiet oder städtebaulicher Entwicklungsbereich; Bescheinigung der Gemeinde (nicht offensichtlich rechtswidrig) mit der Höhe der Kosten; Zuschüsse aus Sanierungsmitteln kürzen die Basis; kein Neubau. Zuständig in Bremen: die Stadtgemeinde.',
      verm: 'ja', para: [es('7h', 'Erhöhte Absetzungen in Sanierungsgebieten')],
      pruefen: 'Welche Bremer Gebiete förmlich festgelegt sind, ließ sich nicht aus einer aktuellen amtlichen Liste belegen (Förderdatenbank-Seite lieferte 404; Gebiet Gröpelingen wurde 2021 aufgehoben). Vor dem Kauf bei der Stadt nachfragen.',
      quelle: 'gesetze-im-internet.de (§ 7h EStG), Abruf ' + ABRUF, rechner: 'st-b' },
    { gruppe: 'umbau', id: 'u-7i', titel: 'Baudenkmal: dieselben Sätze',
      satz: 'Das Gesetz erlaubt bei Baudenkmalen für Baumaßnahmen, die zur Erhaltung oder sinnvollen Nutzung erforderlich sind, ebenfalls 9 Prozent (acht Jahre) und 7 Prozent (vier Jahre).',
      bed: 'Die Maßnahmen müssen vorher mit der Denkmalbehörde abgestimmt sein; Bescheinigung der zuständigen Stelle; Zuschüsse aus öffentlichen Kassen kürzen die Basis. In Bremen: Landesamt für Denkmalpflege.',
      verm: 'ja', para: [es('7i', 'Erhöhte Absetzungen bei Baudenkmalen')],
      pruefen: 'Das Merkblatt des Bremer Landesamts trägt „2020“; Aktualität und Formulare dort prüfen. Eine aktuelle Online-Denkmalliste wurde nicht abgerufen.',
      quelle: 'gesetze-im-internet.de (§ 7i EStG), Merkblatt Landesamt für Denkmalpflege Bremen, Abruf ' + ABRUF, rechner: 'st-b' },
    { gruppe: 'umbau', id: 'u-11ab', titel: 'Erhaltungsaufwand im Sanierungsgebiet oder Denkmal verteilen',
      satz: 'Das Gesetz erlaubt auch hier, Erhaltungsaufwand auf zwei bis fünf Jahre gleichmäßig zu verteilen.',
      bed: 'Gebäude in einem Sanierungsgebiet (§ 11a) oder Baudenkmal (§ 11b).',
      verm: 'ja', para: [es('11a', 'Sonderbehandlung von Erhaltungsaufwand in Sanierungsgebieten'), es('11b', 'Sonderbehandlung bei Baudenkmalen')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§§ 11a, 11b EStG), Abruf ' + ABRUF },
    { gruppe: 'umbau', id: 'u-zuschuss', titel: 'Zuschüsse kürzen die Kosten',
      satz: 'Öffentliche Zuschüsse zu Baumaßnahmen sind keine Mieteinnahmen, vermindern aber die Kosten, die Sie absetzen dürfen.',
      bed: 'Bei Herstellungskosten sinkt die Abschreibungsbasis ab dem Jahr der Bewilligung; bei Erhaltungsaufwand sind nur die um den Zuschuss verminderten Kosten abziehbar.',
      verm: 'ja', para: [{ t: 'Einkommensteuer-Hinweise 2025, R 21.5', u: ESTH_21 }],
      pruefen: 'Ob ein konkreter Zuschuss (zum Beispiel BAFA oder KfW) so behandelt wird, wurde nicht an einer Förderquelle geprüft.',
      quelle: 'Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'umbau', id: 'u-35c', titel: 'Steuerermäßigung für energetische Maßnahmen (§ 35c)',
      satz: 'Diese Ermäßigung gibt es nur für Gebäude, die Sie selbst bewohnen, nicht für vermietete Häuser.',
      bed: 'Selbst genutztes Wohngebäude, älter als zehn Jahre. Als Vermieter behandeln Sie dieselben Maßnahmen als Erhaltungs- oder Herstellungskosten (siehe oben).',
      verm: 'nein', selbstnutzer: true, para: [es('35c', 'Steuerermäßigung für energetische Maßnahmen')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 35c EStG), Abruf ' + ABRUF },
    { gruppe: 'umbau', id: 'u-10f', titel: 'Denkmal oder Sanierungsgebiet selbst bewohnt (§ 10f)',
      satz: 'Diese Regel gilt nur, solange Sie das Gebäude selbst zu Wohnzwecken nutzen, nicht für Vermieter.',
      bed: 'Abzug wie Sonderausgaben, bis zu 9 Prozent in zehn Jahren, nur für die Zeit der Selbstnutzung. Hier nur zur Abgrenzung genannt.',
      verm: 'nein', selbstnutzer: true, para: [es('10f', 'Steuerbegünstigung für zu eigenen Wohnzwecken genutzte Baudenkmale')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 10f EStG), Abruf ' + ABRUF },

    /* ---------- Vermietung ---------- */
    { gruppe: 'vermietung', id: 'v-zinsen', titel: 'Schuldzinsen absetzen',
      satz: 'Das Gesetz erlaubt, die Zinsen für den Kredit als Werbungskosten abzuziehen, soweit das Geld ins vermietete Haus geflossen ist.',
      bed: 'Maßgeblich ist der tatsächliche Verwendungszweck des Darlehens, nicht die Grundschuld auf dem Haus. Nur der Teil für das vermietete Objekt zählt.',
      verm: 'ja', para: [es('9', 'Absatz 1 Satz 3 Nr. 1'), { t: 'Einkommensteuer-Hinweise 2025, H 21.2', u: ESTH_21 }], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 9 EStG), Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-abgaben', titel: 'Grundsteuer und Versicherungen',
      satz: 'Das Gesetz erlaubt, Grundsteuer, öffentliche Abgaben und Versicherungsbeiträge für das vermietete Gebäude als Werbungskosten abzuziehen.',
      bed: 'Die Ausgaben beziehen sich auf das Gebäude oder auf Gegenstände, die der Einnahmeerzielung dienen.',
      verm: 'ja', para: [es('9', 'Absatz 1 Satz 3 Nr. 2')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 9 EStG), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-sonst', titel: 'Fahrten, Hausgeld, Verwaltung',
      satz: 'Gelegentliche Fahrten zum vermieteten Haus und laufende Verwaltungskosten gelten als Werbungskosten; vom Hausgeld zählt nur der laufende Teil.',
      bed: 'Fahrten brauchen einen Nachweis. Die Zuführung zur Instandhaltungsrücklage selbst ist nach allgemeiner Kenntnis nicht abziehbar, erst die tatsächliche Verwendung.',
      verm: 'ja', para: [es('9', 'Absatz 1 Satz 1'), { t: 'Einkommensteuer-Hinweise 2025, R 21.2', u: ESTH_21 }],
      pruefen: 'Höhe der Fahrtkosten-Pauschale, Pauschalen für Kontoführung und die Aussage zur Rücklage sind in der Quelle nicht wörtlich belegt.',
      quelle: 'Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-leerstand', titel: 'Auch bei Leerstand',
      satz: 'Werbungskosten können auch dann anfallen, wenn das Haus vorübergehend leer steht und noch keine Miete kommt.',
      bed: 'Sie müssen die ernsthafte Vermietungsabsicht nachweisen können.',
      verm: 'ja', para: [{ t: 'Einkommensteuer-Hinweise 2025, H 21.2', u: ESTH_21 }], pruefen: '',
      quelle: 'Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-kueche', titel: 'Einbauküche und Möbel',
      satz: 'Eine Einbauküche gilt als ein Wirtschaftsgut, das über zehn Jahre abgeschrieben wird; ein einzelnes Möbelstück bis 800 Euro netto können Sie wohl sofort absetzen.',
      bed: 'Die vollständige Erneuerung einer Einbauküche ist kein Erhaltungsaufwand. Die 800-Euro-Grenze folgt aus der Lesart des Wortlauts von § 9 und § 6 Abs. 2.',
      verm: 'ja', para: [es('6', 'Bewertung, Absatz 2'), { t: 'Einkommensteuer-Hinweise 2025, H 6.4 Einbauküche', u: 'https://esth.bundesfinanzministerium.de/esth/2025/A-Einkommensteuergesetz/II-Einkommen-2-24b/3-Gewinn-4-7i/Paragraf-6/inhalt.html' }],
      pruefen: 'Die 800-Euro-Lesart und die 30-Prozent-Abschreibung für bewegliche Güter bei Vermietern sind nicht abschließend geprüft. Ob die Küche in die 15-%-Grenze zählt, ist nicht geprüft.',
      quelle: 'gesetze-im-internet.de und Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-verluste', titel: 'Verluste aus der Vermietung',
      satz: 'Negative Mieteinkünfte mindern in der Regel Ihr übriges Einkommen; was darüber hinausgeht, kann zurück- oder vorgetragen werden.',
      bed: 'Ausgleich mit anderen Einkunftsarten; Rest bis 1 Mio. Euro (Ehegatten 2 Mio.) in das Vorjahr, Vortrag bis 1 Mio. Euro unbeschränkt, darüber zu 70 Prozent. Bei ständig wechselnden Feriengästen kann das Finanzamt die Einkunftserzielungsabsicht prüfen.',
      verm: 'ja', para: [es('10d', 'Verlustabzug')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 10d EStG), Abruf ' + ABRUF },
    { gruppe: 'vermietung', id: 'v-fristen', titel: 'Fristen und Belege',
      satz: 'Die Steuererklärung (mit Anlage V) ist ohne Steuerberater bis zum 31. Juli des Folgejahres fällig, mit Steuerberater bis Ende Februar des zweiten Folgejahres.',
      bed: 'Heben Sie Kaufvertrag und Rechnungen so lange auf, wie die Abschreibung läuft und darüber hinaus bis zum Verkauf; das ist eine Folgerung aus § 23 Abs. 3 Satz 4, keine ausdrückliche Gesetzesaussage.',
      verm: 'ja', para: [{ t: '§ 149 AO (Abgabe der Steuererklärungen)', u: g('ao_1977', '149') }],
      pruefen: 'Die Aufbewahrungsdauer für Privatvermieter ist nur als eigene Folgerung angegeben.',
      quelle: 'gesetze-im-internet.de (§ 149 AO), Abruf ' + ABRUF },

    /* ---------- Verkauf ---------- */
    { gruppe: 'verkauf', id: 's-frist', titel: 'Die Zehn-Jahres-Frist',
      satz: 'Verkaufen Sie das Haus innerhalb von zehn Jahren nach dem Kauf, ist der Gewinn steuerpflichtig; nach Ablauf der Frist nicht mehr.',
      bed: 'Maßgeblich sind die Daten der notariellen Verträge (Kauf und Verkauf), taggenau; das Gesetz sagt „nicht mehr als zehn Jahre“, die Frist ist also erst überschritten, wenn zwischen den Vertragsdaten mehr als zehn Jahre liegen. Die Selbstnutzung-Ausnahme gilt für Vermieter nicht.',
      verm: 'ja', para: [es('23', 'Private Veräußerungsgeschäfte'), BMF_23],
      pruefen: 'Dass für den Verkauf das Datum des Verkaufsvertrags gilt, ist eine sinngemäße Folgerung aus dem BMF-Schreiben, nicht wörtlich belegt. Ein Referentenentwurf zum Jahressteuergesetz 2026 (19.05.2026) wurde nicht auf Änderungen untersucht.',
      quelle: 'gesetze-im-internet.de (§ 23 EStG), BMF-Schreiben vom 05.10.2000, Abruf ' + ABRUF, rechner: 'st-d' },
    { gruppe: 'verkauf', id: 's-afa', titel: 'Die Abschreibung kommt beim Verkauf zurück',
      satz: 'Beim Verkauf innerhalb der Frist werden die Anschaffungskosten um die bisherige Abschreibung gemindert; der Gewinn fällt dadurch höher aus.',
      bed: 'Gewinn = Verkaufspreis − Verkaufskosten − (Anschaffungskosten − Summe der Abschreibungen). Gilt auch für erhöhte Absetzungen und Sonderabschreibungen.',
      verm: 'ja', para: [es('23', 'Absatz 3 Satz 1 und 4')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 23 EStG), Abruf ' + ABRUF, rechner: 'st-d' },
    { gruppe: 'verkauf', id: 's-freigrenze', titel: 'Freigrenze: unter 1.000 Euro Gewinn',
      satz: 'Bleibt der gesamte Gewinn aus privaten Veräußerungsgeschäften im Jahr unter 1.000 Euro, ist er steuerfrei; ab 1.000 Euro wird der ganze Gewinn besteuert.',
      bed: 'Das ist eine Freigrenze, kein Freibetrag. Sie gilt für den Jahresgesamtgewinn aus allen privaten Veräußerungsgeschäften, bei Ehegatten getrennt je Person.',
      verm: 'ja', para: [es('23', 'Absatz 3 Satz 5')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 23 EStG), Abruf ' + ABRUF, rechner: 'st-d' },
    { gruppe: 'verkauf', id: 's-verlust', titel: 'Verluste beim Verkauf',
      satz: 'Ein Verlust aus dem Verkauf mindert nur Gewinne aus anderen privaten Veräußerungsgeschäften, nicht Ihr übriges Einkommen.',
      bed: 'Im gleichen Jahr nur bis zur Höhe der Gewinne; sonst Rück- oder Vortrag, aber nur gegen Gewinne aus privaten Veräußerungsgeschäften.',
      verm: 'ja', para: [es('23', 'Absatz 3 Sätze 7 und 8')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 23 EStG), Abruf ' + ABRUF },
    { gruppe: 'verkauf', id: 's-kosten', titel: 'Verkaufskosten und Vorfälligkeitsentschädigung',
      satz: 'Kosten, die mit dem Verkauf zusammenhängen, mindern den Gewinn; eine Vorfälligkeitsentschädigung für eine lastenfreie Veräußerung ist zu berücksichtigen.',
      bed: 'Wird nur der Erlös zur Tilgung eines Kredits verwendet, ohne dass die Lastenfreiheit verlangt war, sind das keine Veräußerungskosten. Die Rechnung hier nimmt die Verkaufskosten als Prozentsatz an und rechnet keine Vorfälligkeitsentschädigung.',
      verm: 'ja', para: [{ t: 'Einkommensteuer-Hinweise 2025, H 23', u: ESTH_23 }],
      pruefen: 'Dass Makler und Notar des Verkäufers Veräußerungskosten sind, ist üblich, aber in der Quelle nicht wörtlich aufgezählt. Das BMF-Schreiben vom 27.07.2015 zum nicht steuerbaren Verkauf wurde nicht geladen.',
      quelle: 'Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'verkauf', id: 's-satz', titel: 'Welcher Steuersatz gilt für den Gewinn?',
      satz: 'Der Gewinn wird mit Ihrem persönlichen Einkommensteuersatz besteuert; eine Abgeltungsteuer gibt es hier nicht.',
      bed: 'Tarif 2026: bis 12.348 € Grundfreibetrag, ab 69.879 € zu versteuerndem Einkommen 42 Prozent Grenzsteuersatz. Dazu kommt der Solidaritätszuschlag von 5,5 Prozent, solange Ihre Steuer über der Freigrenze liegt; die Kirchensteuer ist nicht geprüft.',
      verm: 'ja', para: [es('32a', 'Einkommensteuertarif'), { t: '§ 4 SolZG (Zuschlagsatz)', u: g('solzg_1995', '4') }],
      pruefen: 'Kirchensteuersatz Bremen ist nicht geprüft; die Milderungszone des Solidaritätszuschlags rechnet die Seite nicht.',
      quelle: 'gesetze-im-internet.de (§ 32a EStG, § 4 SolZG), Abruf ' + ABRUF, rechner: 'st-d' },

    /* ---------- Fallen ---------- */
    { gruppe: 'fallen', id: 'f-15', titel: 'Falle: Das Haus wird gleich nach dem Kauf renoviert',
      satz: 'Beispiel mit erfundenen Zahlen: Gebäudeanteil 240.000 €, Grenze 36.000 €. Bei 30.000 € netto sind die Kosten sofort abziehbar; bei 40.000 € netto sind alle 40.000 € Herstellungskosten und bringen nur 2 % = 800 € im Jahr.',
      bed: 'Küche, Bäder, Heizung und Fenster überschreiten die Grenze schnell. Je höher der Gebäudeanteil im Kaufpreis, desto höher die Grenze.',
      verm: 'ja', para: [es('6', 'Bewertung, Absatz 1 Nr. 1a')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 6 EStG), Abruf ' + ABRUF, rechner: 'st-a' },
    { gruppe: 'fallen', id: 'f-bescheinigung', titel: 'Falle: Bescheinigung oder Abstimmung zu spät',
      satz: 'Für § 7h und § 7i muss die Bescheinigung der Gemeinde beziehungsweise die Abstimmung mit der Denkmalbehörde vor dem Baubeginn vorliegen.',
      bed: 'Nach dem Merkblatt des Bremer Landesamts kann die fehlende vorherige Abstimmung nicht nachträglich ersetzt werden. Bescheinigt werden nur tatsächlich gezahlte Beträge, nicht die eigene Arbeitsleistung.',
      verm: 'ja', para: [es('7h'), es('7i')],
      pruefen: 'Das Merkblatt trägt „2020“; bitte beim Landesamt die aktuelle Fassung erfragen.',
      quelle: 'gesetze-im-internet.de, Merkblatt Landesamt für Denkmalpflege Bremen, Abruf ' + ABRUF },
    { gruppe: 'fallen', id: 'f-7b-weg', titel: 'Falle: Sonderabschreibung entfällt rückwirkend',
      satz: 'Die Sonderabschreibung nach § 7b wird rückgängig gemacht, wenn die Wohnung nicht zehn Jahre dauerhaft zu Wohnzwecken vermietet wird.',
      bed: 'Das gilt zum Beispiel bei Kurzzeit- oder Beherbergungsnutzung, bei Verkauf innerhalb der zehn Jahre (wenn der Gewinn nicht der Einkommensteuer unterliegt) oder wenn die Baukostenobergrenze durch nachträgliche Kosten überschritten wird. Auch bestandskräftige Bescheide werden geändert.',
      verm: 'ja', para: [es('7b', 'Absatz 4')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 7b EStG), Abruf ' + ABRUF },
    { gruppe: 'fallen', id: 'f-handel', titel: 'Falle: Gewerblicher Grundstückshandel',
      satz: 'Wer mehr als drei Objekte innerhalb von fünf Jahren verkauft, gilt nach der Verwaltungsregel (Drei-Objekt-Grenze) als gewerblich; dann zählt die Zehn-Jahres-Frist nicht mehr.',
      bed: 'Die Fünf-Jahres-Grenze ist nicht starr. Bebaute Grundstücke, die mindestens zehn Jahre vermietet wurden, gehören grundsätzlich noch zur privaten Vermögensverwaltung. Folge bei Gewerblichkeit: Einkünfte aus Gewerbebetrieb und Gewerbesteuer.',
      verm: 'ja', para: [{ t: 'BMF-Schreiben vom 26.03.2004 (Anhang 17 der Einkommensteuer-Hinweise)', u: 'https://esth.bundesfinanzministerium.de/esth/2025/B-Anhaenge/Anhang-17/inhalt.html' }],
      pruefen: 'Neuere BFH-Urteile (zum Beispiel III R 14/23 vom 20.03.2025) sind im Schreiben genannt, ihr Inhalt wurde nicht geprüft.',
      quelle: 'BMF-Schreiben vom 26.03.2004, Tz. 2, 5, 6, Abruf ' + ABRUF },
    { gruppe: 'fallen', id: 'f-privat', titel: 'Falle: Privates und Vermietetes vermischt',
      satz: 'Wird ein Kredit teils privat verwendet, sind nur die Zinsen für den Teil absetzbar, der ins vermietete Haus floss.',
      bed: 'Kaufnebenkosten dürfen nicht fälschlich als Werbungskosten angesetzt werden; sie wirken nur über die Abschreibung.',
      verm: 'ja', para: [es('9', 'Absatz 1 Satz 3 Nr. 1')], pruefen: '',
      quelle: 'gesetze-im-internet.de (§ 9 EStG), Einkommensteuer-Hinweise 2025 (BMF), Abruf ' + ABRUF },
    { gruppe: 'fallen', id: 'f-verbilligt', titel: 'Falle: Miete weit unter der Marktmiete',
      satz: 'Liegt das Entgelt unter 50 Prozent der ortsüblichen Marktmiete, wird die Überlassung in einen entgeltlichen und einen unentgeltlichen Teil aufgeteilt; Werbungskosten gibt es dann nur anteilig.',
      bed: 'Ab 66 Prozent gilt die Vermietung bei auf Dauer angelegter Wohnungsvermietung als entgeltlich. Für Vermietung an Angehörige muss der Vertrag fremdüblich sein.',
      verm: 'ja', para: [es('21', 'Absatz 2')],
      pruefen: 'Für den Bereich zwischen 50 und 66 Prozent regelt der Wortlaut nichts ausdrücklich; die Behandlung ab 2021 und der Fremdvergleich bei Angehörigen sind nicht vollständig belegt.',
      quelle: 'gesetze-im-internet.de (§ 21 EStG), Einkommensteuer-Hinweise 2025, Abruf ' + ABRUF },
    { gruppe: 'fallen', id: 'f-kurzzeit', titel: 'Falle: Kurzzeitvermietung und Monteurzimmer (optional)',
      satz: 'Kurzfristige Beherbergung ist umsatzsteuerpflichtig (7 Prozent), Kleinunternehmer zahlen keine Umsatzsteuer bis 25.000 € im Vorjahr; bei hotelmäßigem Betrieb kann Gewerbesteuer anfallen.',
      bed: 'Die Wohnraumvermietung ist grundsätzlich umsatzsteuerfrei, die kurzfristige Beherbergung nicht. Hotelmäßige Nutzung oder Vermietung nach Art einer Fremdenpension gilt als Gewerbebetrieb.',
      verm: 'ja', para: [{ t: '§ 4 UStG', u: g('ustg_1980', '4') }, { t: '§ 12 UStG', u: g('ustg_1980', '12') }, { t: '§ 19 UStG', u: g('ustg_1980', '19') }],
      pruefen: 'Ob ein konkretes Monteurzimmer-Modell gewerblich ist, ist Einzelfall; die Aussage zur erweiterten Kürzung bei der Gewerbesteuer ist nur eine Einschätzung.',
      quelle: 'gesetze-im-internet.de (UStG), Einkommensteuer-Hinweise 2025 (H 15.7), Abruf ' + ABRUF }
  ];

  window.DATEN.steuern = {
    abruf: ABRUF,
    bericht: 'recherche/14_steuern_sparen.md',
    gruppen: gruppen,
    karten: karten,
    /* Konstanten der Rechner (jeweils mit Quelle, R073) */
    konstanten: {
      grenzeProzent: 15, fristJahre: 10, freigrenze: 1000, soli: 5.5,
      grundfreibetrag: 12348, ab42: 69879,
      tarifQuelle: '§ 32a Abs. 1 EStG, Fassung ab Veranlagungszeitraum 2026, gesetze-im-internet.de, Abruf ' + ABRUF
    }
  };
})();
